### ISSUE TITLE
GET Request Is Registered As POST

### ISSUE THREAD

**Issue by LoganConnor44** [FooSoft/anki-connect#176]
I have just began working with this wonderful add-on, but I've noticed that the endpoints I've expected to be GETs, I had to request as POSTs.

Is this a design error or user error/misunderstand on my part?

Since everything is being routed to just `localhost:8765/` I can imagine a POST is just a catch all and the json passed would specify exactly what is needed. This could be a design I'm just unfamiliar with... I'm more familiar with calls like GET `localhost:8765/notesInfo` and you retrieve data back, then you would call something like POST `localhost:8765/createDeck` and retrieve an https status and possible an ID in the header.

I'm more curious about the design, rather than making a correction. I'm just not familiar with this type of rest service.

Btw - thank you for the add-on this is great.

**Comment by FooSoft** [comment]
There isn't a load of deep design about it -- it could have been done with POST or combination of GET and POST, but there would be no functional difference. Additionally, since I had to hand-roll an HTTP server (since I can't rely on the default Python one being available in target environment on Windows), it would have been more work to implement POST in addition to GET, for really no gain. Whole point is just to get the dirt simplest RPC possible :)
