### ISSUE TITLE
Anki-connect is not working as intended

### ISSUE THREAD

**Issue by whiteflam** [FooSoft/anki-connect#241]
![Sin título](https://user-images.githubusercontent.com/80200592/110238132-13b20380-7f40-11eb-9918-eaee8b740711.png)

The add-on got an update and now the option to add new cards to my deck is not functioning correctly, I don't know what to do, any help would be greatly appreciated

**Comment by lazy-void** [comment]
What version of Anki do you use?

**Comment by whiteflam** [comment]
> What version of Anki do you use?

I'm using Version 2.1.22 (0ecc189a), Python 3.8.0 Qt 5.14.1 PyQt 5.14.1 if that helps as well

**Comment by lazy-void** [comment]
Since some version, Anki has changed what happens when you search the database for a non-existent card/note. This broke several AnkiConnect methods, and to fix this, we now import the NotFoundError exception from Anki. You have this error because your version of Anki doesn't have code with this exception.
@FooSoft fixed this in the last commit and has probably already uploaded the new version to AnkiWeb. If he hasn't already done so, consider updating Anki (latest version is 2.1.41).

**Comment by FooSoft** [comment]
Yeah, compat issue has been fixed and deployed.

**Comment by whiteflam** [comment]
I updated anki and everything is working not only as intended but better than ever, thank you so much for the answers
