### ISSUE TITLE
Unable to install on Anki 2.1.49

### ISSUE THREAD

**Issue by Neosaurus** [FooSoft/anki-connect#320]
Unsure if this is intentional, but reinstalled AnkiConnect on my new Anki install (new machine) and the version updated 5/15 does not allow for installation on 2.1.49, as it says it must use <= 2.1.44. It was working fine before this on 2.1.49 so would appreciate any help! Thanks.

**Comment by Chen03** [comment]
I can't install AnkiConnect too on 2.1.52, and then I tried manually packed it and installed successfully. It seemed that the version check only happens when you are downloading from AnkiWeb.
(Zipped again as github stopped me from uploading ankiaddon file directly...)
[AnkiConnect.ankiaddon.zip](https://github.com/FooSoft/anki-connect/files/8694851/AnkiConnect.ankiaddon.zip)

**Comment by Neosaurus** [comment]
> I can't install AnkiConnect too on 2.1.52, and then I tried manually packed it and installed successfully. It seemed that the version check only happens when you are downloading from AnkiWeb. (Zipped again as github stopped me from uploading ankiaddon file directly...) [AnkiConnect.ankiaddon.zip](https://github.com/FooSoft/anki-connect/files/8694851/AnkiConnect.ankiaddon.zip)

Thanks! This was really helpful. Not well versed enough in these things yet to be able to pack myself
