### ISSUE TITLE
can not add new card with cURL if there is any HTML mark

### ISSUE THREAD

**Issue by valuex** [FooSoft/anki-connect#56]
The following command works right  
`curl localhost:8765 -X POST -d "{\"action\":\"addNote\",\"version\":5,\"params\" :{\"note\" :{\"deckName\":\"Default\",\"modelName\":\"Basic\",\"fields\" :{\"Front\":\"2676\",\"Back\":\"End1123\"},\"tags\":[\"123\"]}}}"`

But when adding some HTML mark to the front or back content, the CMD window says "_The system cannot find the file specified._"

`curl localhost:8765 -X POST -d "{\"action\":\"addNote\",\"version\":5,\"params\" :{\"note\" :{\"deckName\":\"Default\",\"modelName\":\"Basic\",\"fields\" :{\"Front\":\"2676\",\"Back\":\"End1`**`<br>`**`123\"},\"tags\":[\"123\"]}}}"`

please notify that there is a **`<br>`** mark in `\"Back\":\"End1`**`<br>`**`123\"`

**Comment by FooSoft** [comment]
This isn't actually related to AnkiConnect or curl. The problem is that the `<` and `>` characters are used for stream redirection and it appears that `cmd` is not smart enough to recognize it. You have to escape these characters with `^` on Windows. 

See https://stackoverflow.com/questions/251557/escape-angle-brackets-in-a-windows-command-prompt
