### ISSUE TITLE
Is there a place where I can get debug output from AnkiConnect?

### ISSUE THREAD

**Issue by matthew-piziak** [FooSoft/anki-connect#67]
I'm trying to use `anki-editor` from Emacs but I'm getting an error without detailed information. Are logs or debug information available from AnkiConnect? That way I could investigate the problem further.

**Comment by c-okelly** [comment]
AnkiConnect runs within the Anki application itself and as far as I can see it currently does not produce logging. 

One (slowish) way of debugging could be to look at (Anki Debugging Guide)[https://apps.ankiweb.net/docs/addons.html#debugging]. You could insert aqt.utils.showInfo("debug text") or stderr with sys.stderr.write("debug text\n") into the AnkiConnect code and reload the file by restarting Anki to get some output while the program runs within Anki.

**Comment by FooSoft** [comment]
Problem with adding debug prints is that you have to know what you are debugging. Adding debug output for every possible thing that's going on and could possibly need debugging would just create spam. I don't really see a problem with things the way they are right now since you can just go and add print statements to your local version of AnkiConnect as necessary.
